os: linux
dist: bionic

language: shell

branches:
  only:
  - master

cache:
  apt: true
  directories:
  - /usr/local/src

before_install:
  - rm -rf ~/.gnupg

git:
  quiet: true

env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  - sudo apt-get -qq autoremove --purge
addons:
  apt:
    update: true

script:
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes curl wget ccze
  - sudo bash nginx-build.sh --travis || exit 1
  - sudo bash nginx-build.sh --travis --stable  || exit 1
  - sudo bash nginx-build.sh --travis --full  || exit 1
  - sudo bash nginx-build.sh --travis --pagespeed-beta  || exit 1
  - sudo bash nginx-build.sh --travis --libressl  || exit 1
  - sudo bash nginx-build.sh --travis --pagespeed-beta  || exit 1
  - sudo ls -alh /usr/sbin/nginx
  - sudo chown -R travis /usr/local/src
  - sudo chmod 755 /usr/local/src
